// <auto-generated />
using Confere.Telefonia.Web.Dados;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace Confere.Telefonia.Web.Migrations
{
    [DbContext(typeof(TelefoniaContexto))]
    partial class TelefoniaContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Confere.Telefonia.Web.Negocio.Destino", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Destinos");
                });

            modelBuilder.Entity("Confere.Telefonia.Web.Negocio.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<int?>("DestinoFavoritoId");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<int>("SetorId");

                    b.Property<string>("TelefoneFavorito");

                    b.HasKey("Id");

                    b.HasIndex("DestinoFavoritoId");

                    b.HasIndex("SetorId");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("Confere.Telefonia.Web.Negocio.Ligacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contato");

                    b.Property<DateTime>("DataHora");

                    b.Property<int>("DestinoId");

                    b.Property<TimeSpan>("Duracao");

                    b.Property<int>("FuncionarioId");

                    b.Property<string>("Observacao");

                    b.Property<bool>("Particular");

                    b.Property<string>("Telefone");

                    b.Property<int>("TelefonistaId");

                    b.HasKey("Id");

                    b.HasIndex("DestinoId");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("TelefonistaId");

                    b.ToTable("Ligacoes");
                });

            modelBuilder.Entity("Confere.Telefonia.Web.Negocio.Setor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Sigla")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Setores");
                });

            modelBuilder.Entity("Confere.Telefonia.Web.Negocio.Telefonista", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Telefonistas");
                });

            modelBuilder.Entity("Confere.Telefonia.Web.Negocio.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(true);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<byte[]>("ImagemPerfil");

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Senha");

                    b.Property<string>("TextoPapeis")
                        .HasColumnName("Papeis");

                    b.Property<DateTime?>("UltimoLogin");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email");


                    b.HasAlternateKey("Login");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Confere.Telefonia.Web.Negocio.Funcionario", b =>
                {
                    b.HasOne("Confere.Telefonia.Web.Negocio.Destino", "DestinoFavorito")
                        .WithMany()
                        .HasForeignKey("DestinoFavoritoId");

                    b.HasOne("Confere.Telefonia.Web.Negocio.Setor", "Setor")
                        .WithMany("Funcionarios")
                        .HasForeignKey("SetorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Confere.Telefonia.Web.Negocio.Ligacao", b =>
                {
                    b.HasOne("Confere.Telefonia.Web.Negocio.Destino", "Destino")
                        .WithMany()
                        .HasForeignKey("DestinoId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Confere.Telefonia.Web.Negocio.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Confere.Telefonia.Web.Negocio.Telefonista", "Telefonista")
                        .WithMany()
                        .HasForeignKey("TelefonistaId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
